<a href="https://colab.research.google.com/github/ThakurNishant2004/ML-concepts/blob/master/Grid_search_CV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [66]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [67]:
df = sns.load_dataset('iris')

In [68]:
df.shape

(150, 5)

In [69]:
from sklearn.model_selection import train_test_split

In [70]:
X = df.drop('species',axis=1)
y = df['species']

In [71]:
X_train , X_test , y_train , y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [72]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report , confusion_matrix , accuracy_score

In [73]:
model_knn = KNeighborsClassifier(n_neighbors=10)

In [74]:
model_knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=10)

In [75]:
y_pred = model_knn.predict(X_test)
print(model_knn.score(X_test,y_test))
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

1.0
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
1.0

In [76]:
from sklearn.svm import SVC

In [77]:
model_svm = SVC(gamma='auto')

In [78]:
model_svm.fit(X_train,y_train)
model_svm.score(X_test,y_test)

1.0

In [79]:
# Now lets use the grid search CV

In [80]:
from sklearn.model_selection import GridSearchCV

In [81]:
classifier = GridSearchCV((model_svm),{
    'C':[1,10,20,30],
    'kernel':['rbf','linear']
},cv=5,return_train_score=False)

In [82]:
classifier.fit(X,y)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [83]:
classifier.cv_results_

{'mean_fit_time': array([0.00259037, 0.00153966, 0.00213509, 0.00170755, 0.00191474,
        0.00207715, 0.00244064, 0.00188165]),
 'std_fit_time': array([9.33156228e-04, 5.98409546e-05, 3.18017869e-04, 4.09422392e-05,
        1.27462952e-04, 3.10823236e-04, 3.27273577e-04, 8.34090830e-05]),
 'mean_score_time': array([0.00174294, 0.00118494, 0.00149245, 0.00124054, 0.0014751 ,
        0.00157113, 0.00173278, 0.00136013]),
 'std_score_time': array([5.06838122e-04, 4.59075578e-05, 2.62989911e-04, 1.56060578e-05,
        2.88842234e-04, 1.51008268e-04, 1.60514777e-04, 7.64562549e-05]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        , 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
        0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.93333333, 0.9       ]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667, 0.96      , 0.96      ]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
        0.0421637 , 0.03887301, 0.04898979]),
 'rank_test_score': array([1, 1, 1, 4, 5, 6, 7, 7], dtype=int32)}

In [84]:
results = pd.DataFrame(classifier.cv_results_)

In [85]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002590,0.000933,0.001743,0.000507,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.001540,0.000060,0.001185,0.000046,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.002135,0.000318,0.001492,0.000263,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.001708,0.000041,0.001241,0.000016,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.001915,0.000127,0.001475,0.000289,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,5
5,0.002077,0.000311,0.001571,0.000151,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.002441,0.000327,0.001733,0.000161,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,7
7,0.001882,0.000083,0.001360,0.000076,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,7

In [86]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667
6       30          rbf         0.960000
7       30       linear         0.960000

In [87]:
classifier2 = GridSearchCV((model_knn),
    {
        'n_neighbors':[1,2,3,4,5,6,7,8,9,10],
        'weights':['uniform','distance'],
        'algorithm':['auto', 'ball_tree', 'kd_tree', 'brute'],
    },cv=5 , return_train_score = False
)

In [88]:
classifier2.fit(X,y)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(n_neighbors=10),
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                         'weights': ['uniform', 'distance']})

In [89]:
result = classifier2.cv_results_

In [90]:
results = pd.DataFrame(result)

In [91]:
results[['param_n_neighbors','param_weights','param_algorithm','mean_test_score']]

    param_n_neighbors param_weights param_algorithm  mean_test_score
0                   1       uniform            auto         0.960000
1                   1      distance            auto         0.960000
2                   2       uniform            auto         0.946667
3                   2      distance            auto         0.960000
4                   3       uniform            auto         0.966667
..                ...           ...             ...              ...
75                  8      distance           brute         0.980000
76                  9       uniform           brute         0.980000
77                  9      distance           brute         0.973333
78                 10       uniform           brute         0.986667
79                 10      distance           brute         0.986667

[80 rows x 4 columns]